# Generated by Django 5.2.17 on 2026-08-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
