# Generated by Django 5.2.17 on 2026-08-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_profile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, help_text="Only meaningful from the recipient's side."),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
